module.exports = {
  spriteName: 'sprite-base',
  orientation: 'vertical',
  background: '#FFFFFF',
  format: 'png',
  source: process.cwd() + '/sprites/',
  cssPath: process.cwd() + '/styles/',
  imgPath: process.cwd() + '/images/',
  processor: 'css',
  opacity: 0,
  template: null,
  prefix: 'icon',
  useImport: false,
  indexName: 'sprites-index',
  multiFolders: false,
}
